name: tiktac_app
description: "Aplicación de cronómetro con historial y títulos personalizados."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.0
  intl: ^0.20.3
  share_plus: ^13.3.0
  permission_handler: ^12.0.3
  uuid: ^4.6.0
  vibration: ^3.2.0
  screenshot: ^3.0.0
  simple_pip_mode: ^1.1.0
  path_provider: ^2.1.6
  flutter_foreground_task: ^10.0.0
  flutter_ringtone_player: ^4.0.0+4
  file_picker: ^12.0.0-beta.7
  shared_preferences: ^2.5.5
  flutter_bloc: ^9.1.1
  get_it: ^9.2.1
  logger: ^2.7.0
  injectable: ^2.5.0
  equatable: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  injectable_generator: ^2.6.2
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
